_base_: [base.yaml, ../exp11_random_learnable_12.yaml]
experiment: {name: gray_no_bn_exp11_random_learnable_4, result_root: results/grayscale_no_batchnorm}
dataset: {grayscale: true}
model: {args: {input_channels: 1, spatial_kernels: 4, use_batchnorm: false}}
