_base_: [base.yaml, ../exp1_random_learnable_3.yaml]
experiment: {name: gray_exp1_random_learnable_1, result_root: results/grayscale}
dataset: {grayscale: true}
model: {args: {input_channels: 1, spatial_kernels: 1}}
