_base_: [base.yaml, ../exp8_random_learnable_6.yaml]
experiment: {name: gray_exp8_random_learnable_2, result_root: results/grayscale}
dataset: {grayscale: true}
model: {args: {input_channels: 1, spatial_kernels: 2}}
